services:
  jogojusto-api:
    container_name: jogojusto
    build:
      context: ./JogoJusto
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    restart: always
            