// <auto-generated />
using System;
using JogoJusto.AppDta;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace JogoJusto.Migrations
{
    [DbContext(typeof(JogoJustoDbContext))]
    [Migration("20251202000316_InitalBaseline")]
    partial class InitalBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JogoJusto.Models.DepartamentoModel", b =>
                {
                    b.Property<int>("IdDepartamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_DEPTO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDepartamento"));

                    b.Property<int>("EmpresaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("T_EMPRESA_ID_EMPRESA");

                    b.Property<int?>("GerenteId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("GERENTE_ID");

                    b.Property<string>("NomeDepartamento")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NM_DEPTO");

                    b.HasKey("IdDepartamento");

                    b.HasIndex("EmpresaId");

                    b.ToTable("T_DEPTO", (string)null);
                });

            modelBuilder.Entity("JogoJusto.Models.DesenvolvimentoModel", b =>
                {
                    b.Property<int>("IdDesenvolvimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_DESENV");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDesenvolvimento"));

                    b.Property<byte[]>("Certificado")
                        .HasColumnType("BLOB")
                        .HasColumnName("CERTIFICADO");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("DATE")
                        .HasColumnName("DT_CONCLUSAO");

                    b.Property<DateTime>("DataRegistroDeDados")
                        .HasColumnType("DATE")
                        .HasColumnName("DT_REGISTRO");

                    b.Property<string>("DescricaoRegistro")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_REGISTRO");

                    b.Property<decimal?>("DuracaoHoras")
                        .HasPrecision(6, 2)
                        .HasColumnType("NUMBER(6,2)")
                        .HasColumnName("DURACAO_HORAS");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("T_FUNCIONARIO_ID_FUNC");

                    b.Property<string>("NomeTreinamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NM_TREINAMENTO");

                    b.Property<string>("StatusRegistro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("ST_REGISTRO");

                    b.Property<string>("TipoRegistro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TIPO_REGISTRO");

                    b.Property<string>("Treinamento")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("PROVEDOR_TREINAMENTO");

                    b.HasKey("IdDesenvolvimento");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("T_DESENV", (string)null);
                });

            modelBuilder.Entity("JogoJusto.Models.EmpresaModel", b =>
                {
                    b.Property<int>("EmpresaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_EMPRESA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpresaId"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("NR_CNPJ");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("END_EMPRESA");

                    b.Property<string>("InscricaoEstadual")
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("NR_INSCRI_EST");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NM_EMPRESA");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NR_TELEFONE");

                    b.HasKey("EmpresaId");

                    b.ToTable("T_EMPRESA", (string)null);
                });

            modelBuilder.Entity("JogoJusto.Models.EsgLogModel", b =>
                {
                    b.Property<int>("IdEsgLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_LOG");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEsgLog"));

                    b.Property<string>("AcaoRealizada")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TIPO_ACAO");

                    b.Property<DateTime>("DataAcao")
                        .HasColumnType("DATE")
                        .HasColumnName("DT_REGISTRO");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_DEPTO");

                    b.Property<decimal>("Nota")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("Recomendacao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("RECOMENDACAO");

                    b.HasKey("IdEsgLog");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("T_ESG_LOG", (string)null);
                });

            modelBuilder.Entity("JogoJusto.Models.FuncionarioModel", b =>
                {
                    b.Property<int>("FuncionarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_FUNC");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FuncionarioId"));

                    b.Property<string>("Cargo")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("CARGO_FUN");

                    b.Property<string>("Cpf")
                        .HasMaxLength(16)
                        .HasColumnType("NVARCHAR2(16)")
                        .HasColumnName("NR_CPF");

                    b.Property<DateTime?>("DataContratacao")
                        .HasColumnType("DATE")
                        .HasColumnName("DT_ADMISSAO");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("DATE")
                        .HasColumnName("DT_NASC_FUN");

                    b.Property<int?>("DepartamentoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("T_DEPTO_ID_DEPTO");

                    b.Property<string>("Genero")
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("GENERO_FUN");

                    b.Property<int?>("MentorId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MENTOR_ID");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_FUNC");

                    b.Property<string>("Raca")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("COR_FUN");

                    b.Property<decimal?>("Salario")
                        .IsRequired()
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("SAL_BASE");

                    b.Property<string>("StPcd")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("ST_PCD");

                    b.Property<string>("TipoPcd")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TIPO_PCD");

                    b.HasKey("FuncionarioId");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("MentorId");

                    b.ToTable("T_FUNCIONARIO", (string)null);
                });

            modelBuilder.Entity("JogoJusto.Models.MetaEsgModel", b =>
                {
                    b.Property<int>("IdMetaEsg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_META");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMetaEsg"));

                    b.Property<DateTime?>("AtualizacaoDados")
                        .HasColumnType("DATE")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<string>("DescricaoMetaEsg")
                        .HasMaxLength(400)
                        .HasColumnType("NVARCHAR2(400)")
                        .HasColumnName("DS_META");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("T_EMPRESA_ID_EMPRESA");

                    b.Property<DateTime>("PrazoMetaEsg")
                        .HasColumnType("DATE")
                        .HasColumnName("PRAZO_META");

                    b.Property<string>("StatusRegistro")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ST_REGISTRO");

                    b.Property<string>("TipoMetaEsg")
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR2(60)")
                        .HasColumnName("TIPO_META");

                    b.Property<decimal?>("ValorAtualMetaEsg")
                        .HasPrecision(5, 2)
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("VL_ATUAL");

                    b.Property<decimal>("ValorReferenciaMetaEsg")
                        .HasPrecision(5, 2)
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("VL_REFERENCIA");

                    b.HasKey("IdMetaEsg");

                    b.HasIndex("EmpresaId");

                    b.ToTable("T_METAS_ESG", (string)null);
                });

            modelBuilder.Entity("JogoJusto.Models.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TIPO");

                    b.HasKey("Id");

                    b.ToTable("T_USUARIO", (string)null);
                });

            modelBuilder.Entity("JogoJusto.Models.DepartamentoModel", b =>
                {
                    b.HasOne("JogoJusto.Models.EmpresaModel", "Empresa")
                        .WithMany("Departamentos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("JogoJusto.Models.DesenvolvimentoModel", b =>
                {
                    b.HasOne("JogoJusto.Models.FuncionarioModel", "Funcionario")
                        .WithMany("Desenvolvimentos")
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("JogoJusto.Models.EsgLogModel", b =>
                {
                    b.HasOne("JogoJusto.Models.DepartamentoModel", "Departamento")
                        .WithMany("EsgLogs")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("JogoJusto.Models.FuncionarioModel", b =>
                {
                    b.HasOne("JogoJusto.Models.DepartamentoModel", "Departamento")
                        .WithMany("Funcionarios")
                        .HasForeignKey("DepartamentoId");

                    b.HasOne("JogoJusto.Models.FuncionarioModel", "Mentor")
                        .WithMany("Mentorados")
                        .HasForeignKey("MentorId");

                    b.Navigation("Departamento");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("JogoJusto.Models.MetaEsgModel", b =>
                {
                    b.HasOne("JogoJusto.Models.EmpresaModel", "Empresa")
                        .WithMany("MetasEsg")
                        .HasForeignKey("EmpresaId");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("JogoJusto.Models.DepartamentoModel", b =>
                {
                    b.Navigation("EsgLogs");

                    b.Navigation("Funcionarios");
                });

            modelBuilder.Entity("JogoJusto.Models.EmpresaModel", b =>
                {
                    b.Navigation("Departamentos");

                    b.Navigation("MetasEsg");
                });

            modelBuilder.Entity("JogoJusto.Models.FuncionarioModel", b =>
                {
                    b.Navigation("Desenvolvimentos");

                    b.Navigation("Mentorados");
                });
#pragma warning restore 612, 618
        }
    }
}
