// <auto-generated />
using System;
using JogoJusto.AppDta;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace JogoJusto.Migrations
{
    [DbContext(typeof(JogoJustoDbContext))]
    [Migration("20251127180745_PrimeiraMigration")]
    partial class PrimeiraMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JogoJusto.Models.DepartamentoModel", b =>
                {
                    b.Property<int>("IdDepartamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDepartamento"));

                    b.Property<int>("EmpresaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("GerenteId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NomeDepartamento")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.HasKey("IdDepartamento");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("JogoJusto.Models.DesenvolvimentoModel", b =>
                {
                    b.Property<int>("IdDesenvolvimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDesenvolvimento"));

                    b.Property<DateTime>("DataConclusao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("DataRegistroDeDados")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("DescricaoRegistro")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("DuracaoHoras")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NomeTreinamento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<byte[]>("Orgao")
                        .IsRequired()
                        .HasColumnType("RAW(2000)");

                    b.Property<string>("StatusRegistro")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TipoRegistro")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Treinamento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdDesenvolvimento");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("DesenvolvimentoModel");
                });

            modelBuilder.Entity("JogoJusto.Models.EmpresaModel", b =>
                {
                    b.Property<int>("EmpresaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpresaId"));

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("InscricaoEstadual")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("EmpresaId");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("JogoJusto.Models.EsgLogModel", b =>
                {
                    b.Property<int>("IdEsgLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEsgLog"));

                    b.Property<string>("AcaoRealizada")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DataAcao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("DepartamentoIdDepartamento")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Recomendacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdEsgLog");

                    b.HasIndex("DepartamentoIdDepartamento");

                    b.ToTable("EsgLogModel");
                });

            modelBuilder.Entity("JogoJusto.Models.FuncionarioModel", b =>
                {
                    b.Property<int>("FuncionarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FuncionarioId"));

                    b.Property<string>("CargaHoraria")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("NVARCHAR2(16)");

                    b.Property<DateTime>("DataContratacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("DepartamentoIdDepartamento")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("DescricaoCargaHoraria")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("MentorFuncionarioId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Raca")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("Salario")
                        .HasColumnType("NUMBER(18,2)");

                    b.Property<bool>("StPcd")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("TipoPcd")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("FuncionarioId");

                    b.HasIndex("DepartamentoIdDepartamento");

                    b.HasIndex("MentorFuncionarioId");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("JogoJusto.Models.MetaEsgModel", b =>
                {
                    b.Property<int>("IdMetaEsg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMetaEsg"));

                    b.Property<DateTime>("AtualizacaoDados")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("DescricaoMetaEsg")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("PrazoMetaEsg")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("TipoMetaEsg")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("ValorAtualMetaEsg")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal>("ValorReferenciaMetaEsg")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasKey("IdMetaEsg");

                    b.HasIndex("EmpresaId");

                    b.ToTable("MetaEsg");
                });

            modelBuilder.Entity("JogoJusto.Models.TokenModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Token")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TokenId")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TokenName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Tokem");
                });

            modelBuilder.Entity("JogoJusto.Models.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("JogoJusto.Models.DepartamentoModel", b =>
                {
                    b.HasOne("JogoJusto.Models.EmpresaModel", "Empresa")
                        .WithMany("Departamentos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("JogoJusto.Models.DesenvolvimentoModel", b =>
                {
                    b.HasOne("JogoJusto.Models.FuncionarioModel", "Funcionario")
                        .WithMany("Desenvolvimentos")
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("JogoJusto.Models.EsgLogModel", b =>
                {
                    b.HasOne("JogoJusto.Models.DepartamentoModel", "Departamento")
                        .WithMany("EsgLogs")
                        .HasForeignKey("DepartamentoIdDepartamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("JogoJusto.Models.FuncionarioModel", b =>
                {
                    b.HasOne("JogoJusto.Models.DepartamentoModel", "Departamento")
                        .WithMany("Funcionarios")
                        .HasForeignKey("DepartamentoIdDepartamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JogoJusto.Models.FuncionarioModel", "Mentor")
                        .WithMany("Mentorados")
                        .HasForeignKey("MentorFuncionarioId");

                    b.Navigation("Departamento");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("JogoJusto.Models.MetaEsgModel", b =>
                {
                    b.HasOne("JogoJusto.Models.EmpresaModel", "Empresa")
                        .WithMany("MetasEsg")
                        .HasForeignKey("EmpresaId");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("JogoJusto.Models.DepartamentoModel", b =>
                {
                    b.Navigation("EsgLogs");

                    b.Navigation("Funcionarios");
                });

            modelBuilder.Entity("JogoJusto.Models.EmpresaModel", b =>
                {
                    b.Navigation("Departamentos");

                    b.Navigation("MetasEsg");
                });

            modelBuilder.Entity("JogoJusto.Models.FuncionarioModel", b =>
                {
                    b.Navigation("Desenvolvimentos");

                    b.Navigation("Mentorados");
                });
#pragma warning restore 612, 618
        }
    }
}
