// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:4.0.0.0
//      SpecFlow Generator Version:4.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace JogoJustoTestes.BDD.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "4.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class GerenciamentoDeEmpresasFeature : object, Xunit.IClassFixture<GerenciamentoDeEmpresasFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Empresa.feature"
#line hidden
        
        public GerenciamentoDeEmpresasFeature(GerenciamentoDeEmpresasFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunnerForAssembly(null, TechTalk.SpecFlow.xUnit.SpecFlowPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt"), "BDD/Features", "Gerenciamento de Empresas", "Como administrador da plataforma JogoJusto\r\nQuero gerenciar empresas cadastradas\r" +
                    "\nPara garantir a integridade dos dados organizacionais no contexto ESG", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            TechTalk.SpecFlow.xUnit.SpecFlowPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 8
#line hidden
#line 9
await testRunner.GivenAsync("que o administrador está autenticado com email \"isabella@example.com\" e password " +
                    "\"SenhaForte123\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cadastrar nova empresa com sucesso")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Empresas")]
        [Xunit.TraitAttribute("Description", "Cadastrar nova empresa com sucesso")]
        [Xunit.TraitAttribute("Category", "CadastrarEmpresa")]
        public async System.Threading.Tasks.Task CadastrarNovaEmpresaComSucesso()
        {
            string[] tagsOfScenario = new string[] {
                    "CadastrarEmpresa"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cadastrar nova empresa com sucesso", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 12
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "nome",
                            "cnpj",
                            "endereco"});
                table1.AddRow(new string[] {
                            "Empresa XYZ",
                            "12.345.678/0001-90",
                            "Rua Exemplo, 123"});
#line 13
await testRunner.WhenAsync("ele envia uma requisição POST para \"/api/empresa\" com o seguinte payload:", ((string)(null)), table1, "Quando ");
#line hidden
#line 16
 await testRunner.ThenAsync("ele deve receber uma resposta com status code 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
#line 17
 await testRunner.AndAsync("o corpo da resposta deve conter a mensagem \"Empresa criada com sucesso.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Listar todas as empresas com sucesso")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Empresas")]
        [Xunit.TraitAttribute("Description", "Listar todas as empresas com sucesso")]
        [Xunit.TraitAttribute("Category", "ListarEmpresas")]
        public async System.Threading.Tasks.Task ListarTodasAsEmpresasComSucesso()
        {
            string[] tagsOfScenario = new string[] {
                    "ListarEmpresas"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Listar todas as empresas com sucesso", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 20
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 21
await testRunner.WhenAsync("ele envia uma requisição GET para \"/api/empresa\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 22
 await testRunner.ThenAsync("ele deve receber uma resposta com status code 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
#line 23
 await testRunner.AndAsync("a resposta deve conter uma lista de empresas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Buscar empresa existente por ID")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Empresas")]
        [Xunit.TraitAttribute("Description", "Buscar empresa existente por ID")]
        [Xunit.TraitAttribute("Category", "BuscarEmpresaPorID")]
        public async System.Threading.Tasks.Task BuscarEmpresaExistentePorID()
        {
            string[] tagsOfScenario = new string[] {
                    "BuscarEmpresaPorID"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Buscar empresa existente por ID", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 26
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 27
await testRunner.WhenAsync("ele envia uma requisição GET para \"/api/empresa/1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 28
 await testRunner.ThenAsync("ele deve receber uma resposta com status code 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
#line 29
 await testRunner.AndAsync("o corpo da resposta deve conter o campo \"empresaId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Buscar empresa inexistente por ID")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Empresas")]
        [Xunit.TraitAttribute("Description", "Buscar empresa inexistente por ID")]
        [Xunit.TraitAttribute("Category", "BuscarEmpresaInexistente")]
        public async System.Threading.Tasks.Task BuscarEmpresaInexistentePorID()
        {
            string[] tagsOfScenario = new string[] {
                    "BuscarEmpresaInexistente"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Buscar empresa inexistente por ID", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 32
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 33
await testRunner.WhenAsync("ele envia uma requisição GET para \"/api/empresa/999\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 34
 await testRunner.ThenAsync("ele deve receber uma resposta com status code 404", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
#line 35
 await testRunner.AndAsync("o corpo da resposta deve conter a mensagem \"Empresa não encontrada.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "4.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await GerenciamentoDeEmpresasFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await GerenciamentoDeEmpresasFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
