// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:4.0.0.0
//      SpecFlow Generator Version:4.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace JogoJustoTestes.BDD.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "4.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class GerenciamentoDeFuncionariosFeature : object, Xunit.IClassFixture<GerenciamentoDeFuncionariosFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Funcionario.feature"
#line hidden
        
        public GerenciamentoDeFuncionariosFeature(GerenciamentoDeFuncionariosFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunnerForAssembly(null, TechTalk.SpecFlow.xUnit.SpecFlowPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt"), "BDD/Features", "Gerenciamento de Funcionários", "Como departamento de recursos humanos de uma empresa, \r\nquero gerenciar os funcio" +
                    "nários cadastrados para garantir \r\na diversidade e inclusão nos departamentos.", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            TechTalk.SpecFlow.xUnit.SpecFlowPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 8
#line hidden
#line 9
await testRunner.GivenAsync("que o administrador está autenticado com email \"isabella@example.com\" e password " +
                    "\"SenhaForte123\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cadastrar novo funcionário com sucesso")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Funcionários")]
        [Xunit.TraitAttribute("Description", "Cadastrar novo funcionário com sucesso")]
        [Xunit.TraitAttribute("Category", "CadastrarFuncionario")]
        public async System.Threading.Tasks.Task CadastrarNovoFuncionarioComSucesso()
        {
            string[] tagsOfScenario = new string[] {
                    "CadastrarFuncionario"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cadastrar novo funcionário com sucesso", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 12
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "nome",
                            "cargo",
                            "departamentoId",
                            "genero",
                            "raca",
                            "cpf",
                            "dataNascimento",
                            "dataContratacao"});
                table2.AddRow(new string[] {
                            "Silvana Barros",
                            "Analista",
                            "4",
                            "Feminino",
                            "Parda",
                            "457.646.900-28",
                            "1990-05-15",
                            "2026-05-02"});
#line 13
await testRunner.WhenAsync("ele envia uma requisição POST para \"/api/funcionario\" com os dados do funcionário" +
                        ":", ((string)(null)), table2, "Quando ");
#line hidden
#line 16
 await testRunner.ThenAsync("ele deve receber uma resposta com status code 200 para funcionario", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
#line 17
 await testRunner.AndAsync("o corpo da resposta do funcionario deve conter a mensagem \"Funcionário criado com" +
                        " sucesso.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Listar todos os funcionários com sucesso")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Funcionários")]
        [Xunit.TraitAttribute("Description", "Listar todos os funcionários com sucesso")]
        [Xunit.TraitAttribute("Category", "ListarFuncionarios")]
        public async System.Threading.Tasks.Task ListarTodosOsFuncionariosComSucesso()
        {
            string[] tagsOfScenario = new string[] {
                    "ListarFuncionarios"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Listar todos os funcionários com sucesso", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 20
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 21
 await testRunner.WhenAsync("ele solicita a lista de funcionários cadastrados enviando uma requisição GET para" +
                        " \"/api/funcionario\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 22
 await testRunner.ThenAsync("a resposta deve conter uma lista de funcionários", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Buscar funcionário existente por ID")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Funcionários")]
        [Xunit.TraitAttribute("Description", "Buscar funcionário existente por ID")]
        [Xunit.TraitAttribute("Category", "BuscarFuncionarioPorID")]
        public async System.Threading.Tasks.Task BuscarFuncionarioExistentePorID()
        {
            string[] tagsOfScenario = new string[] {
                    "BuscarFuncionarioPorID"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Buscar funcionário existente por ID", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 26
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 27
 await testRunner.WhenAsync("ele envia uma requisição GET para \"/api/funcionario/2\" para buscar um funcionário" +
                        " existente por ID", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 28
 await testRunner.ThenAsync("ele deve receber uma resposta com status code 200 para funcionario", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
#line 29
 await testRunner.AndAsync("o corpo da resposta deve conter o campo \"funcionarioId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Buscar funcionário inexistente por ID")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Funcionários")]
        [Xunit.TraitAttribute("Description", "Buscar funcionário inexistente por ID")]
        [Xunit.TraitAttribute("Category", "BuscarFuncionarioInexistente")]
        public async System.Threading.Tasks.Task BuscarFuncionarioInexistentePorID()
        {
            string[] tagsOfScenario = new string[] {
                    "BuscarFuncionarioInexistente"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Buscar funcionário inexistente por ID", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 32
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 33
 await testRunner.WhenAsync("ele envia uma requisição GET para \"/api/funcionario/25\" para buscar um funcionári" +
                        "o inexistente por ID", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 34
 await testRunner.ThenAsync("ele deve receber uma resposta com status code 404", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
#line 35
 await testRunner.AndAsync("o corpo da resposta deve conter a mensagem \"Funcionário não encontrado.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "4.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await GerenciamentoDeFuncionariosFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await GerenciamentoDeFuncionariosFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
