// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:4.0.0.0
//      SpecFlow Generator Version:4.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace JogoJustoTestes.BDD.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "4.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class MetaFeature : object, Xunit.IClassFixture<MetaFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Meta.feature"
#line hidden
        
        public MetaFeature(MetaFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunnerForAssembly(null, TechTalk.SpecFlow.xUnit.SpecFlowPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt"), "BDD/Features", "Meta", "Com o login de um Admin na plataforma jogojusto,\r\no admin tem a capacidade de cri" +
                    "ar metas para as empresas cadastradas,\r\ncom o objetivo de promover práticas sust" +
                    "entáveis e responsáveis no contexto ESG.", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            TechTalk.SpecFlow.xUnit.SpecFlowPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 9
#line hidden
#line 10
    await testRunner.GivenAsync("que o administrador está autenticado com email \"isabella@example.com\" e password " +
                    "\"SenhaForte123\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cadastrar nova meta para empresa com sucesso")]
        [Xunit.TraitAttribute("FeatureTitle", "Meta")]
        [Xunit.TraitAttribute("Description", "Cadastrar nova meta para empresa com sucesso")]
        [Xunit.TraitAttribute("Category", "CriarMeta")]
        public async System.Threading.Tasks.Task CadastrarNovaMetaParaEmpresaComSucesso()
        {
            string[] tagsOfScenario = new string[] {
                    "CriarMeta"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cadastrar nova meta para empresa com sucesso", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 13
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
await this.FeatureBackgroundAsync();
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "tipoMetaEsg",
                            "descricaoMetaEsg",
                            "valorReferenciaMetaEsg",
                            "valorAtualMetaEsg",
                            "prazoMetaEsg",
                            "empresaId"});
                table2.AddRow(new string[] {
                            "Redução de Emissões",
                            "Reduzir as emissões de carbono em 20% até 2025",
                            "20",
                            "0",
                            "2026-12-31T00:00:00.000Z",
                            "2"});
#line 14
    await testRunner.WhenAsync("ele envia uma requisição POST para criar \"/api/metaesg\" com o seguinte payload:", ((string)(null)), table2, "Quando ");
#line hidden
#line 17
    await testRunner.ThenAsync("ele deve receber uma resposta com status code 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 18
    await testRunner.AndAsync("o corpo da resposta deve conter a mensagem \"Meta ESG criada com sucesso\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Listar metas cadastradas com sucesso")]
        [Xunit.TraitAttribute("FeatureTitle", "Meta")]
        [Xunit.TraitAttribute("Description", "Listar metas cadastradas com sucesso")]
        [Xunit.TraitAttribute("Category", "ListarMetas")]
        public async System.Threading.Tasks.Task ListarMetasCadastradasComSucesso()
        {
            string[] tagsOfScenario = new string[] {
                    "ListarMetas"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Listar metas cadastradas com sucesso", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 21
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
await this.FeatureBackgroundAsync();
#line hidden
#line 22
    await testRunner.WhenAsync("ele envia uma requisição GET para listarS \"/api/metaesg\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 23
    await testRunner.ThenAsync("ele deve receber uma resposta com status code 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 24
    await testRunner.AndAsync("o corpo da resposta deve conter a lista de metas cadastradas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Atualizar meta existente com sucesso")]
        [Xunit.TraitAttribute("FeatureTitle", "Meta")]
        [Xunit.TraitAttribute("Description", "Atualizar meta existente com sucesso")]
        [Xunit.TraitAttribute("Category", "AtualizarMeta")]
        public async System.Threading.Tasks.Task AtualizarMetaExistenteComSucesso()
        {
            string[] tagsOfScenario = new string[] {
                    "AtualizarMeta"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Atualizar meta existente com sucesso", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 27
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
await this.FeatureBackgroundAsync();
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "tipoMetaEsg",
                            "descricaoMetaEsg",
                            "valorAtualMetaEsg",
                            "prazoMetaEsg",
                            "empresaId"});
                table3.AddRow(new string[] {
                            "Redução de Emissões",
                            "Reduzir as emissões de carbono em 25% até 2025",
                            "25",
                            "2026-12-31T00:00:00.000Z",
                            "2"});
#line 28
    await testRunner.WhenAsync("ele envia uma requisição PUT para  \"/api/metaesg/6\" com o seguinte payload:", ((string)(null)), table3, "Quando ");
#line hidden
#line 31
    await testRunner.ThenAsync("ele deve receber uma resposta com status code 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 32
    await testRunner.AndAsync("o corpo da resposta deve conter a mensagem \"Meta ESG atualizada com sucesso.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Pesquisar meta existente por ID")]
        [Xunit.TraitAttribute("FeatureTitle", "Meta")]
        [Xunit.TraitAttribute("Description", "Pesquisar meta existente por ID")]
        [Xunit.TraitAttribute("Category", "PesquisarMetaPorID")]
        public async System.Threading.Tasks.Task PesquisarMetaExistentePorID()
        {
            string[] tagsOfScenario = new string[] {
                    "PesquisarMetaPorID"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pesquisar meta existente por ID", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 35
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
await this.FeatureBackgroundAsync();
#line hidden
#line 36
    await testRunner.ThenAsync("ele envia uma requisição GET para obter por ID \"/api/metaesg/2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 37
    await testRunner.ThenAsync("ele deve receber uma resposta com status code 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 38
    await testRunner.AndAsync("o corpo da resposta deve conter os detalhes da meta com ID 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Deletar meta existente com sucesso")]
        [Xunit.TraitAttribute("FeatureTitle", "Meta")]
        [Xunit.TraitAttribute("Description", "Deletar meta existente com sucesso")]
        [Xunit.TraitAttribute("Category", "DeletarMeta")]
        public async System.Threading.Tasks.Task DeletarMetaExistenteComSucesso()
        {
            string[] tagsOfScenario = new string[] {
                    "DeletarMeta"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Deletar meta existente com sucesso", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 41
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
await this.FeatureBackgroundAsync();
#line hidden
#line 42
    await testRunner.ThenAsync("ele deve enviara uma requisição DELETE para \"/api/metaesg/2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 43
    await testRunner.ThenAsync("ele deve receber uma resposta com status code 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 44
    await testRunner.AndAsync("o corpo da resposta deve conter a mensagem \"Meta ESG excluída com sucesso.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "4.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await MetaFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await MetaFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
